# Generated by Django 5.0.6 on 2024-06-11 20:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blogpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from="title",
                unique=True,
                verbose_name="Ссылка для поста",
            ),
        ),
    ]
