# Generated by Django 5.0.6 on 2024-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(unique=True, verbose_name="Ссылка для поста"),
        ),
    ]
